#!/bin/bash

folder="/usr/share/texgen"
cp texgen /usr/bin/texgen
if test -d $folder || mkdir $folder
then
    cp -r template/ $folder
fi

install -g 0 -o 0 -m 0644 texgen.1 /usr/local/man/man1/
gzip /usr/local/man/man1/texgen.1
