#!/bin/bash

usage()
{
    echo ""
    echo "Usage: texgen [-s|-b|--plain|--custom] [-g,-L,--no-library] [-p,--language] name"
    echo ""
    echo "generates a TEX file in given 'name' folder based on templates"
    echo ""
    echo "TEMPLATE OPTIONS"
    echo " -b, --beamer     : adds the template for a beamer class"
    echo " -s, --scientific : adds a scientific article template"
    echo " --plain          : adds a plain article class. (default)"
    echo " --custom=NAME    : adds a custom template"
    echo ""
    echo "STYLE OPTIONS"
    echo " -g, --git        : adds a git.sty package to the .tex file"
    echo " -L, --layout     : adds a layout.sty package to the .tex file"
    echo " --no-library     : omits to add a custom.sty package to the .tex file"
    echo ""
    echo "OTHER OPTIONS"
    echo " -p, --project    : adds the selected template into a 'doc' folder instead"
    echo " --language=LANG  : adds selected translation of given template instead"
    echo ""
}

version()
{
    echo "texgen 4.0 (beta) - by Daniel Foehn aka Gnomengineer"
}

error()
{
    echo " [EE] - Error: $1";
    exit
}

info()
{
    echo " [II] - Info: $1";
}

command=$(basename $0)

if [ $# -eq 0 ] 
then
    error "no parameter given. see $command -h for help"
elif [ $# -gt 3 ]
then
    error "too many parameter given. see $command -h for help"
fi

template_dir=/usr/share/texgen/template
custom_style="custom.sty"
page_style="pageformatting.sty"
file="plain_doc.tex"
sysspec=0
project=0

while [ "$1" != "" ]
do
    case $1 in
        -h | --help)
            usage;
            exit;
            ;;
        -v | --version)
            version;
            exit;
            ;;
        -t | --type)
            shift
            case $1 in
                beamer)
                    file="beamer.tex";
                    ;;
                sysspec)
                    file="sysspec_eng.tex";
                    sysspec=1;
                    ;;
                sysspecGER)
                    file="sysspec_ger.tex";
                    sysspec=1;
                    ;;
                concept)
                    file="sysspec_eng.tex";
                    pmp="pmp_eng.tex";
                    sysspec=1;
                    ;;
                conceptGER)
                    file="sysspec_ger.tex";
                    pmp="pmp_ger.tex";
                    sysspec=1;
                    ;;
                project)
                    file="sysspec_eng.tex";
                    pmp="pmp_eng.tex";
                    project=1;
                    sysspec=1;
                    ;;
                *)
                    error "missing type for latex document. see $command -h for help";
                    ;;
            esac
            ;;
        *)
            documentname=$1;
            folder=$1;
            ;;
    esac
    shift
done

if [ "$folder" == "" ]
then
    error "you need to give a directory name"
fi

if [ $project -eq 1 ]
then
    folder="doc"
fi

mkdir $folder

if test -d $folder
then
    cd $folder 

    if [ $sysspec -eq 1 ]
    then
        filename="SysSpec_$documentname"
    else
        filename=$documentname
    fi

    cp $template_dir/$file $filename.tex
    if [ "$pmp" != "" ]
    then
        cp $template_dir/$pmp "PMP_$documentname.tex"
    fi
    cp $template_dir/$custom_style $custom_style
    cp $template_dir/$page_style $page_style

    info "latex structure successfully created!"
else
    error "folder could not be created" 
fi
